# -*- coding: utf-8 -*-
"""
Created on Sat Jul 17 08:06:45 2021

@author: Luis Manuel Méndez
"""
"""
CIRCUNFERENCIA:
La circunferencia, es un lugar geométrico de un punto que
se mueve en un plano, de tal manera que se conserva siempre
a una distancia constante de un punto fijo de ese plano.
Ese punto fijo se llama centro de la circunferencia y la
distancia constante se llama radio.
"""
print()
print("Autor: Luis Manuel Méndez")
print()
print("            ECUACIÓN CANÓNICA:")
print()
print("x^2 + y^2 = r^2             con centro (0,0) y radio r")
print()
print("           ECUACIÓN ORDINARIA:")
print()
print("(x - h)^2 + (y - k)^2 = r^2    con centro (h,k) y radio r")
print()
print("           ECUACIÓN GENERAL:")
print()    
print("Ax^2 + Cy^2 + Dx + Ey + F = 0     para A = C")
print()
print("x^2 + y^2 + Dx + Ey + F = 0")
print()
print("     Por favor, ingresa los valores de A, C, D, Y y F:")
print("    --------------------------------------------------3")
print("              Ax^2 + Cy^2 + Dx + Ey + F = 0")
print()
A = int(input("A: "))
C = int(input("C: "))
D = int(input("D: "))
E = int(input("E: ")) 
F = int(input("F: "))
print()
print("           ",A,"x^2 + ",C,"y^2 + ",D,"x +",E,"y +",F,"= 0")
print()
print("              Completación de cuadrados: ")
print()
print("((",A,")x^2 + (",D,")x) + ((",C,")y^2 + (",E,")y) = (",- F,")")  
print()
print(A,"(x^2 + (",D/A,")x) +",C,"(y^2 + (",E/C,")y) = (",- F,")") 
print()
print("                       A = C")
print()
print(A,"(x^2 + (",D/A,")x +",((D**2)/(4*A**2)),") +",A,"(y^2 + (",E/A,")y + (",((E**2)/(4*A**2)),") = (",- F,") + (",((A*D**2)/(4*A**2)),") + (",(A*E**2)/(4*A**2),")")             
print()
print(A,"(x + (",D/(2*A),"))^2 +",A,"(y + (",E/(2*A),"))^2 = (",- F,") + (",((A*D**2)/(4*A**2)),") + (",(A*E**2)/(4*A**2),")")
print()
print("(x + (",D/(2*A),"))^2 + (y + (",E/(2*A),"))^2 = (",- F,") + (",((A*D**2)/(4*A**2)),") + (",(A*E**2)/(4*A**2),")")
print("                                     ----------------------------")
print("                                                 ",A)
print()
print("C ((",-D/(2*A),"),(",-E/(2*A),"))")
h = -D/(2*A)
k = -E/(2*A)
print()
r2 = ((-F+(A*D**2)/(4*A**2)+(A*E**2)/(4*A**2))/A)
print("r^2 = ",round(r2,3))
r = round(pow(r2,0.5),3)
print()
print("r = ",r)
print("                 GRÁFICA                    ")
print("                   .║.                      ")
print("                .   ║   .                   ")
print("              .     ║     . r = ",r,"       ")
print("             .      ║       .               ")
print("          ===.======╬=======.======╬= ",k," ")
print("              .     ║     .        ║        ")
print("                .   ║   .          ║        ")
print("                   .║.             ║        ")
print("--------------------║--------------║-       ")
print("                    ║              ║        ")
print("                  ",h,"                     ")
print("FIN")